### ISSUE TITLE
训练参数问题

### ISSUE THREAD

**Issue by han508** [FreedomIntelligence/HuatuoGPT-II#12]
请问代码中我看step数为：int(len(train_dataloader) * (args.n_epochs + 0.35))，请问0.35是什么意思呢？是为了在最后学习率不要衰减太低而影响sft的性能吗

还有想请教一下，我看epoch为2，在sampler的时候，会在一个epoch的末尾增大sft的数据比例，请问作者有没有试验过，在所有epcoh都是最后环节增大sft数据比例，和只在最后一个环节增加SFT数据比例哪个效果好呢？

**Comment by jymChen** [comment]
@han508 你好，
int(len(train_dataloader) * (args.n_epochs + 0.35))只是为了学习率最后不会太低而导致最尾部的数据没有学习到。epoch设置为2只是为了调大lr_schedule的步数，然后结合 int(len(train_dataloader) * (args.n_epochs + 0.35))可以使得在学习率收敛接近0之前把所有数据训完。虽然epoch设置为2，实际上训练的epoch只为1。

很抱歉，这部分代码没写清楚，epoch设为2和用int(len(train_dataloader) * (args.n_epochs + 0.35))只是为了让学习率在最后保持高一些而已，本身模型训练只走一个epoch。
