### ISSUE TITLE
论文一阶段复现疑问

### ISSUE THREAD

**Issue by zhou-wjjw** [FreedomIntelligence/HuatuoGPT-II#15]
按照之前我的理解是需要经过继续预训练才能够让模型学习到专有领域知识。
当前一阶段训练：没有继续预训练而是只使用了预训练的语料进行采样和SFT这个过程，最终的结论是可以既能够学习到领域知识也能够实现非常好的对齐效果，并且超出之前的两阶段训练。
有几个问题再请教下：
1.大致使用了多少算力（多少张卡）
2.训练了多久
3.SFT训练方式是全参微调还是lora微调
之前在论文中没有看到这部分，我打算和团队进行复现。
非常期待您的回答，谢谢。

**Comment by jymChen** [comment]
@zhou-wjjw 您好，
我们的方法是将预训练的语料用大模型进行改写成QA的方式对齐SFT数据，其次，采用优先级采样策略将两阶段的数据进行混合训练，这些策略都有助于缓解灾难性遗忘。下面是对您问题的回复：
1&2. 7B模型用了一台8卡A100训练的，训练时间差不多3天。
3. 训练方式是全微调，不用lora。
可以考虑采用我们一阶段的训练方法，其中数据拼接的训练方式也可以加快模型训练。
