### ISSUE TITLE
模型推理问题

### ISSUE THREAD

**Issue by Yanhong-Li** [FreedomIntelligence/HuatuoGPT-II#26]
您好，我复现了一阶段训练，但是保存下来的模型是下图所示的格式的：
![image](https://github.com/FreedomIntelligence/HuatuoGPT-II/assets/41324434/ccfd406d-de81-4a5c-b2b2-b9f065e96367)

请问这种形式的参数文件怎么推理呢？需不需要做进一步的转换？

**Comment by Yanhong-Li** [comment]
我执行了zero_to_fp32.py把参数转换成了pytorch_model.bin，然后使用transformers接口进行推理，不知道这样对不对？

**Comment by Yanhong-Li** [comment]
@jymChen 请问您推理的时候模型怎么转换的呢，能否提供一下相关代码，非常感谢！

**Comment by jymChen** [comment]
> 我执行了zero_to_fp32.py把参数转换成了pytorch_model.bin，然后使用transformers接口进行推理，不知道这样对不对？

对的，用目录下面的zero_to_fp32.py转成 pytorch_model.bin就可以推理啦。

**Comment by Yanhong-Li** [comment]
> > 我执行了zero_to_fp32.py把参数转换成了pytorch_model.bin，然后使用transformers接口进行推理，不知道这样对不对？
> 
> 对的，用目录下面的zero_to_fp32.py转成 pytorch_model.bin就可以推理啦。

好的，非常感谢！
